Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2023-10, with the labels that each got.

#98 Added Kuudra Command
  README.md
  src/instance/minecraft/CommandsManager.ts
  src/instance/minecraft/commands/KuudraCommand.ts
  src/type/hypixel-api-reborn.d.ts
Labels: enhancement

#105 Changed Restart & Shutdown Names
  README.md
  src/Application.ts
  src/common/ApplicationEvent.ts
  src/instance/discord/CommandManager.ts
  src/instance/discord/commands/ReconnectCommand.ts
  src/instance/discord/commands/RestartCommand.ts
  src/instance/discord/commands/ShutdownCommand.ts
  src/instance/minecraft/MinecraftInstance.ts
Labels: documentation, enhancement, Core

#114 Stop Minecraft From reconnecting after being banned
  src/instance/minecraft/handlers/StateHandler.ts
Labels: bug

#115 Command help
  src/instance/minecraft/CommandsManager.ts
  src/instance/minecraft/commands/BitchesCommand.ts
  src/instance/minecraft/commands/CalculateCommand.ts
  src/instance/minecraft/commands/CataCommand.ts
  src/instance/minecraft/commands/EightBallCommand.ts
  src/instance/minecraft/commands/ExplainCommand.ts
  src/instance/minecraft/commands/GuildCommand.ts
  src/instance/minecraft/commands/IqCommand.ts
  src/instance/minecraft/commands/KuudraCommand.ts
  src/instance/minecraft/commands/LevelCommand.ts
  src/instance/minecraft/commands/NetworthCommand.ts
  src/instance/minecraft/commands/RockPaperScissorsCommand.ts
  src/instance/minecraft/commands/RouletteCommand.ts
  src/instance/minecraft/commands/RunsCommand.ts
  src/instance/minecraft/commands/SecretsCommand.ts
  src/instance/minecraft/commands/SkillCommand.ts
  src/instance/minecraft/commands/WeightCommand.ts
  src/instance/minecraft/common/ChatInterface.ts
Labels: enhancement

#120 Help command to discord
  src/instance/minecraft/CommandsManager.ts
  src/instance/minecraft/commands/ExplainCommand.ts
  src/instance/minecraft/commands/SecretsCommand.ts
Labels: bug, enhancement

#122 Improved regex to detect guild mutes & swapped embed title to responsible user
  src/instance/minecraft/chat/MuteChat.ts
  src/instance/minecraft/chat/UnmuteChat.ts
Labels: bug

#133 Remove GlobalChat
  config_example.yaml
  src/Application.ts
  src/ApplicationConfig.ts
  src/common/ClientInstance.ts
  src/instance/globalChat/GlobalChatInstance.ts
  src/instance/globalChat/common/GlobalConfig.ts
Labels: Core

#134 Fix truncate message and filter
  src/instance/discord/ChatManager.ts
Labels: bug

#136 Feature: Remove discord tracking from images
  src/util/DiscordMessageUtil.ts
Labels: enhancement
