Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2024-05, with the labels that each got.

#171 docs: Improve readme
  README.md
Labels: documentation

#173 Better english
  README.md
  src/common/application-event.ts
  src/common/client-instance.ts
  src/instance/metrics/application-metrics.ts
  src/instance/minecraft/chat-manager.ts
  src/instance/minecraft/minecraft-instance.ts
  src/plugins/auto-restart-plugin.ts
  src/plugins/dark-auction-plugin.ts
  src/plugins/example-plugin.ts
  src/plugins/limbo-plugin.ts
  src/plugins/punishment-plugin.ts
  src/plugins/reaction-plugin.ts
  src/plugins/starfall-cult-plugin.ts
Labels: documentation

#178 https://imgur.com/a/gD7Welp
  src/instance/minecraft/chat/repeat.ts
Labels: bug

#175 fix(punishments): fix punishments various issues
  src/instance/discord/commands/punishments.ts
  src/instance/minecraft/chat/public.ts
  src/plugins/punishment-plugin.ts
  src/util/punished-users.ts
Labels: bug

#180 fix(discord): /list fails to respond if hypixel request fails
  src/instance/discord/commands/list.ts
Labels: bug

#181 chore(metrics): Replace a deprecated node method
  src/instance/metrics/metrics-instance.ts
Labels: dependencies

#182 Chore: Improve plugin example code and fix some typos
  src/common/application-event.ts
  src/plugins/example-plugin.ts
Labels: documentation

#176 Asianification
  src/instance/commands/triggers/calculate.ts
Labels: enhancement

#170 Implementation of the RTCA command, in response to Add command to check for runs counts till Class average 50 #91
  src/instance/commands/commands-instance.ts
  src/instance/commands/triggers/runs-to-class-average.ts
  src/instance/discord/discord-instance.ts
  src/types/hypixel-api-reborn.d.ts
Labels: enhancement

#183 feat(commands): add soopy api commands
  src/instance/commands/commands-instance.ts
  src/instance/commands/triggers/soopy.ts
Labels: enhancement

#184 fix(commands): soopy commands args aren't added properly
  src/instance/commands/triggers/soopy.ts
Labels: bug

#187 fix(commands): Soopy command cache shared between users
  src/instance/commands/triggers/soopy.ts
Labels: bug

#191 feat(discord): add discord status and activity
  src/instance/discord/discord-instance.ts
  src/instance/discord/handlers/status-handler.ts
Labels: enhancement

#192 feat(discord): preserves /list original sorting order
  src/instance/discord/commands/list.ts
Labels: enhancement

#188 feat(plugins): Add warp-plugin
  README.md
  config_example.yaml
  src/plugins/warp-plugin.ts
Labels: enhancement
