Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2024-09, with the labels that each got.

#167 Adding profanity filter for messages originating from minecraft
  .gitignore
  src/application.ts
  src/common/application-event-ti.ts
  src/common/application-event.ts
  src/instance/discord/chat-manager.ts
  src/instance/discord/discord-instance.ts
  src/instance/logger/logger-instance.ts
  src/instance/minecraft/chat-manager.ts
  src/instance/minecraft/chat/officer.ts
  src/instance/minecraft/chat/public.ts
Labels: enhancement

#209 chore(workflow): update workflows
  .github/workflows/codeql.yml
  .github/workflows/dependency-review.yml
Labels: dependencies

#211 fix(deps): revert and ensure bad-words doesn't update
  package-lock.json
  package.json
  src/application.ts
  src/types/bad-words.d.ts
Labels: bug, dependencies

#210 feat(workflow): add publish docker/release workflow
  .github/workflows/publish.yml
  Dockerfile
Labels: documentation

#213 chore(app): bump to minor version 3.2.0
  package-lock.json
  package.json
Labels: dependencies

#218 docs(app): Document how to use Docker
  README.md
  index.ts
  src/application.ts
  src/util/shared-util.ts
Labels: documentation

#219 refactor(app): enable @typescript-eslint/naming-convention
  .eslintrc.json
  index.ts
  src/application.ts
  src/common/application-event.ts
  src/common/client-instance.ts
  src/configuration-parser.ts
  src/instance/commands/common/command-interface.ts
  src/instance/commands/common/util.ts
  src/instance/commands/triggers/bits.ts
  src/instance/commands/triggers/networth.ts
  src/instance/commands/triggers/slayer.ts
  src/instance/commands/triggers/soopy.ts
  src/instance/commands/triggers/weight.ts
  src/instance/discord/chat-manager.ts
  src/instance/discord/commands/accept.ts
  src/instance/discord/commands/connectivity.ts
  src/instance/discord/commands/demote.ts
  src/instance/discord/commands/invite.ts
  src/instance/discord/commands/list.ts
  src/instance/discord/commands/log.ts
  src/instance/discord/commands/promote.ts
  src/instance/discord/commands/punishments.ts
  src/instance/discord/commands/setrank.ts
  src/instance/discord/common/chat-triggers.ts
  src/instance/discord/discord-instance.ts
  src/instance/discord/discord-pager.ts
  src/instance/minecraft/chat-manager.ts
  src/instance/minecraft/handlers/state-handler.ts
  src/instance/minecraft/minecraft-instance.ts
  src/plugins/auto-restart-plugin.ts
  src/plugins/starfall-cult-plugin.ts
  src/plugins/warp-plugin.ts
  src/types/hypixel-api-reborn.d.ts
  src/util/mojang.ts
  src/util/punished-users.ts
  src/util/shared-util.ts
Labels: documentation

#220 chore(lint): lint with a better PascalCase
  .eslintrc.json
  src/application-config-ti.ts
  src/application-config.ts
  src/common/application-event.ts
  src/common/client-instance.ts
  src/configuration-parser.ts
  src/instance/commands/triggers/8ball.ts
  src/instance/commands/triggers/rock-paper-scissors.ts
  src/instance/commands/triggers/runs-to-class-average.ts
  src/instance/commands/triggers/skills.ts
  src/instance/discord/command-manager.ts
  src/instance/discord/commands/about.ts
  src/instance/discord/commands/accept.ts
  src/instance/discord/commands/connectivity.ts
  src/instance/discord/commands/demote.ts
  src/instance/discord/commands/invite.ts
  src/instance/discord/commands/list.ts
  src/instance/discord/commands/log.ts
  src/instance/discord/commands/override.ts
  src/instance/discord/commands/ping.ts
  src/instance/discord/commands/promote.ts
  src/instance/discord/commands/punishments.ts
  src/instance/discord/commands/reconnect.ts
  src/instance/discord/commands/restart.ts
  src/instance/discord/commands/setrank.ts
  src/instance/discord/common/command-interface.ts
  src/instance/discord/discord-pager.ts
  src/instance/minecraft/chat/repeat.ts
  src/instance/minecraft/common/proxy-handler.ts
Labels: documentation

#221 fix(app): hotfix proxy config
  src/application-config-ti.ts
  src/application-config.ts
Labels: bug

#222 fix(commands): Commands crashes
  src/instance/commands/commands-instance.ts
  src/instance/commands/common/util.ts
  src/instance/commands/triggers/bits.ts
  src/instance/commands/triggers/calculate.ts
  src/instance/commands/triggers/catacomb.ts
  src/instance/commands/triggers/guild.ts
  src/instance/commands/triggers/kuudra.ts
  src/instance/commands/triggers/level.ts
  src/instance/commands/triggers/networth.ts
  src/instance/commands/triggers/runs-to-class-average.ts
  src/instance/commands/triggers/runs.ts
  src/instance/commands/triggers/secrets.ts
  src/instance/commands/triggers/skills.ts
  src/instance/commands/triggers/slayer.ts
  src/instance/commands/triggers/soopy.ts
  src/types/hypixel-api-reborn.d.ts
Labels: bug

#225 chore(discord): temp disable profanity warnings notifications on officer chat
  src/instance/discord/discord-instance.ts
Labels: Misc

#223 Made museumData optional
  src/instance/commands/triggers/networth.ts
Labels: bug

#226 fix(minecraft): fix minecraft fails due to too many reqeusts
  src/instance/minecraft/handlers/error-handler.ts
Labels: bug

#195 Add a message ingame confirming the use of the !warp command.
  src/common/application-event-ti.ts
  src/common/application-event.ts
  src/instance/commands/commands-instance.ts
  src/instance/commands/common/command-interface.ts
  src/instance/discord/discord-instance.ts
  src/instance/logger/logger-instance.ts
  src/instance/minecraft/minecraft-instance.ts
  src/plugins/warp-plugin.ts
Labels: enhancement

#227 fix(discord): commands send "event.instanceName" instead of the instance name
  src/instance/discord/discord-instance.ts
Labels: bug

#229 chore(deps): update deps
  package-lock.json
  src/instance/socket/server-socket.ts
  src/types/minecraft-protocol.ts
Labels: dependencies
