Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2024-10, with the labels that each got.

#232 refactor(core): do various fixes to minecraft
  src/common/bridge-handler.ts
  src/instance/discord/bridge-handler.ts
  src/instance/discord/discord-instance.ts
  src/instance/minecraft/bridge-handler.ts
  src/instance/minecraft/chat-manager.ts
  src/instance/minecraft/client-session.ts
  src/instance/minecraft/common/proxy-handler.ts
  src/instance/minecraft/handlers/error-handler.ts
  src/instance/minecraft/handlers/selfbroadcast-handler.ts
  src/instance/minecraft/handlers/sendchat-handler.ts
  src/instance/minecraft/handlers/state-handler.ts
  src/instance/minecraft/minecraft-instance.ts
  src/plugins/limbo-plugin.ts
  src/plugins/warp-plugin.ts
Labels: bug, enhancement, Core

#233 fix(minecraft): hotfix remove testing configs
  src/instance/minecraft/minecraft-instance.ts
Labels: bug

#234 feat(commands): add !personalbest command
  src/instance/commands/commands-instance.ts
  src/instance/commands/triggers/personal-best.ts
  src/instance/commands/triggers/runs.ts
  src/instance/commands/triggers/secrets.ts
  src/types/hypixel-api-reborn.d.ts
Labels: enhancement

#236 feat(commands): add !parties
  README.md
  package-lock.json
  package.json
  src/instance/commands/commands-instance.ts
  src/instance/commands/triggers/party.ts
Labels: enhancement

#243 Readd profileByUuid method to mojang.ts
  src/util/mojang.ts
Labels: dependencies
