Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2024-07, with the labels that each got.

#199 fix(discord): /invite doesn't detect full guild
  src/instance/discord/common/chat-triggers.ts
Labels: bug

#200 chore(deps): update all main packages
  package-lock.json
  package.json
Labels: dependencies

#201 fix(commands): switch !rtca args
  src/instance/commands/triggers/runs-to-class-average.ts
Labels: bug

#202 Add catacombs alias for command
  src/instance/commands/triggers/catacomb.ts
Labels: enhancement
