Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2024-11, with the labels that each got.

#244 feat(commands): add magical power command !mp
  src/instance/commands/commands-instance.ts
  src/instance/commands/triggers/magicalpower.ts
Labels: enhancement

#247 https://imgur.com/a/rP78rDo
  src/instance/commands/triggers/magicalpower.ts
Labels: Misc

#246 docs: Improve documentation and add more aliases to commands
  README.md
  src/instance/commands/triggers/party.ts
Labels: documentation
