Repository aidn3/hypixel-guild-discord-bridge, pull requests merged in 2024-04, with the labels that each got.

#163 Better Punishment system
  .eslintignore
  .eslintrc.json
  .gitignore
  .prettierignore
  config_example.yaml
  index.ts
  package.json
  src/application.ts
  src/common/application-event-ti.ts
  src/common/application-event.ts
  src/instance/commands/triggers/roulette.ts
  src/instance/discord/chat-manager.ts
  src/instance/discord/command-manager.ts
  src/instance/discord/commands/about.ts
  src/instance/discord/commands/accept.ts
  src/instance/discord/commands/connectivity.ts
  src/instance/discord/commands/demote.ts
  src/instance/discord/commands/invite.ts
  src/instance/discord/commands/kick.ts
  src/instance/discord/commands/list.ts
  src/instance/discord/commands/log.ts
  src/instance/discord/commands/mute.ts
  src/instance/discord/commands/override.ts
  src/instance/discord/commands/ping.ts
  src/instance/discord/commands/promote.ts
  src/instance/discord/commands/punishments.ts
  src/instance/discord/commands/reconnect.ts
  src/instance/discord/commands/restart.ts
  src/instance/discord/commands/setrank.ts
  src/instance/discord/commands/unmute.ts
  src/instance/discord/common/command-interface.ts
  src/instance/discord/discord-pager.ts
  src/instance/minecraft/chat-manager.ts
  src/instance/minecraft/chat/mute.ts
  src/instance/minecraft/chat/public.ts
  src/instance/minecraft/chat/unmute.ts
  src/instance/minecraft/common/chat-interface.ts
  src/plugins/punishment-plugin.ts
  src/util/mojang.ts
  src/util/punished-users.ts
  tsconfig.json
Labels: enhancement, Core

#162 Bitscommand
  src/instance/commands/commands-instance.ts
  src/instance/commands/common/command-interface.ts
  src/instance/commands/triggers/bits.ts
Labels: enhancement

#169 feat(plugin): Create auto-restart-plugin
  config_example.yaml
  src/plugins/auto-restart-plugin.ts
Labels: enhancement

#168 chore(docs): Clarify what to put in "username" field
  src/common/application-event.ts
Labels: documentation
